# Generated by Django 5.0.3 on 2024-09-05 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdStorageTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('current_location', models.CharField(max_length=255)),
                ('availability_status', models.BooleanField(default=True)),
                ('temperature_conditions', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DecompositionGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=20)),
                ('decomposition_method', models.TextField()),
                ('partner_company', models.CharField(max_length=100)),
                ('estimated_time', models.DurationField()),
                ('eco_friendly_rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('Cooked', 'Cooked Food'), ('Uncooked', 'Uncooked Ingredients'), ('Packaged', 'Packaged Food'), ('Non-edible', 'Non-edible Food')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('pickup_time', models.DateTimeField()),
                ('requires_cold_storage', models.BooleanField(default=False)),
                ('needs_decomposition', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
